### ISSUE TITLE
Result for a connection without parameters

### ISSUE THREAD

**Issue by rafaelstz** [tiagosampaio/ApiPlus#3]
<img width="927" alt="screen shot 2016-10-26 at 00 03 56" src="https://cloud.githubusercontent.com/assets/610598/19710839/14683826-9b10-11e6-9f51-ccc70ae8d478.png">

<img width="927" alt="screen shot 2016-10-26 at 00 07 35" src="https://cloud.githubusercontent.com/assets/610598/19710862/39a8f03a-9b10-11e6-9d3e-14a67bdc1ce4.png">

**Comment by tiagosampaio** [comment]
Thanks, Rafael.

How did you make the call to the API? You need to send a request body in the following format:

`
{
  "resource": "catalog_product.list"
}
`

Regards,

\- Tiago

**Comment by rafaelstz** [comment]
@tiagosampaio here works well, in this report I did want to report the error without parameters, without callback message, is it the normal comportment?

**Comment by tiagosampaio** [comment]
I just made the adjustments.

Thanks,

\- Tiago
